version: "3"
services:
  lambda:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 9000:8080
    environment:
      DYNAMODB_ENDPOINT: dynamodb:8000
      DYNAMODB_TABLE: example-dev
      AWS_ACCESS_KEY_ID: DUMMYIDEXAMPLE
      AWS_SECRET_ACCESS_KEY: DUMMYEXAMPLEKEY
    depends_on:
      - dynamodb
    volumes:
      - .:/go/src/lambda
  dynamodb:
    image: amazon/dynamodb-local
    user: root
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath ./data
    ports:
      - 8000:8000
    volumes:
      - dynamodb-data:/home/dynamodblocal/data

volumes:
  dynamodb-data:
    driver: local
