FROM golang:1.22-bullseye
RUN go install github.com/cosmtrek/air@latest
WORKDIR /go/src/lambda
COPY go.mod go.sum ./
RUN go mod download
COPY ./ .
ENV GOOS=linux GOARCH=amd64

ADD https://github.com/aws/aws-lambda-runtime-interface-emulator/releases/latest/download/aws-lambda-rie /usr/bin/aws-lambda-rie
RUN chmod 755 /usr/bin/aws-lambda-rie
CMD ["air", "-c", ".air.toml"]
